[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'yegappan/grep'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-entire'
